version: '3.1'

services:
  db:
    image: postgres:latest
    env_file:
      - ../.env
    volumes:
       - db:/postgres/data
    ports:
      - "5432:5432"

  web:
    ports:
      - "8000:8000"
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

volumes:
  db:
